name: Test

on:
  push:
    branches: [ development, 'feature/**', 'release/**', 'master' ]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x,15.x,16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
    - uses: szenius/set-timezone@v1.0
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        timezoneLinux: "America/Bogota"
    - run: yarn install
    - run: yarn test